### ISSUE TITLE
Stealing items from claimed chunks with hopper minecarts

### ISSUE THREAD

**Issue by JustAlittleWolf** [cjburkey01/ClaimChunk#252]
**Versions**
Spigot Version: newest Paper version
ClaimChunk Version: 0.0.23-RC7

**Describe the bug**
You can steal items from a chest in a claimed chunk by moving a hopper minecart into the chunk, then moving it under the chest (assuming there is an air block under the chest) and then simply breaking the hopper minecart (yes you can do that in a claimed chunk)

**To Reproduce**
1. Place a hoppe rminecart on rails outside of a claimed chunk
2. push it off the rails and into the chunk
3. push it under the chest
4. break the minecart

**Expected behavior**
1. The hopper minecart can't be broken in a claimed chunk.
*or*
2. you cannot push the hopper minecart in a claimed chunk

**Comment by cjburkey01** [comment]
In theory this should be solved in https://github.com/cjburkey01/ClaimChunk/commit/9cddce5d3bb709a9afad42dae511a3b347836253

Could you try this version? [claimchunk-0.0.23-RC8-plugin.jar.zip](https://github.com/cjburkey01/ClaimChunk/files/9175930/claimchunk-0.0.23-RC8-plugin.jar.zip)

**Comment by JustAlittleWolf** [comment]
I tried the version you sent here, unfortunately it didn't fix the issue. I can still break the minecart and with this version I can also directly open the hopper minecart on a claimed chunk.

**Comment by cjburkey01** [comment]
Hm, that seems slightly wrong

**Comment by sluhtie** [comment]
Is this still in development? I'm having the same issues
